Add hint to reboot if openvpn is running; Add new chapter into debian/NEWS

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -42,6 +42,10 @@ case "$1" in
       echo "$b" | grep -q '\*' && continue
       ln -sf "/run/openvpn/$b" "/run/sendsigs.omit.d/openvpn.$b"
     done
+    if pidof -c /usr/sbin/openvpn >/dev/null; then
+        echo "A reboot is required to replace the running openvpn." >&2
+        echo "Please reboot the system as soon as possible." >&2
+    fi
   ;;
 esac
 
